package core

internal object Versions {
    const val buildGradle_version = "7.2.1"
    const val kotlin_version = "1.6.21"
    const val firebaseCrashAnalyticGradleVersion = "2.7.1"
    const val googleServicesVersion =  "4.3.8"

    const val appcompat_version = "1.4.2"
    const val preference_version = "1.2.0"
    const val swipeLayout_version = "1.1.0"
    const val coreKtx_version = "1.8.0"
    const val constraintLayout_version = "2.1.4"
    const val material_version = "1.7.0-alpha02"
    const val activity_version = "1.4.0"
    const val fragment_version = "1.4.1"
    const val lifecycle_version = "2.4.0"
    const val recyclerview_version = "1.2.1"
    const val card_view_version = "1.0.0"
    const val hilt_android_version = "2.39.1"
    const val nav_version = "2.4.2"
    const val coroutines_version = "1.6.2"
    const val retrofit_version = "2.9.0"
    const val okhttp3_version = "4.9.3"
    const val timberVersion = "5.0.1"
    const val viewStateLayoutVersion = "1.0.4"
    const val circleImageViewVersion = "3.1.0"
    const val picassoVersion = "2.8"
    const val rxJava3_version = "3.1.5"
    const val rx_android3_version = "3.0.0"
    const val sdp_version = "1.0.6"
    const val leakcanary_version = "2.7"
    const val dots_indicator_version = "4.3"
    const val play_core_version = "1.10.3"
    const val play_ktx_version = "1.8.1"
    const val facebook_version = "12.0.1"
    const val facebook_marketing_version = "7.0.1"
    const val map_version = "18.0.2"
    const val map_location_version = "19.0.0"
    const val map_place_version = "2.6.0"
    const val firebase_bom_version= "30.1.0"
    const val room_version = "2.4.2"
    const val alerter_version = "7.2.4"
    const val epoxy_version = "5.0.0-beta03"
    const val image_zoom_version = "2.3.0"

    const val junit = "4.13.2"
    const val ext_junit = "1.1.3"
    const val espresso = "3.4.0"
}